 1-Create an array of 10 fives

In [143]:
import numpy as np
arr=(np.ones(10)*5)
print(arr)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


2-Create an array of all the even integers from 10 to 50

In [4]:
arr2=np.arange(10,50,2)
arr2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

3-Create a 3x3 matrix with values ranging from 0 to 8

#

In [8]:
arr3=np.linspace(0,8,9).reshape(3,3)
print(arr3)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


4-Create the following matrix:

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [14]:
arr4=np.linspace(0.01,1,100).reshape(10,10)
print(arr4)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


5-So Provided that we have a set of data. How can we find the median? (implement median function)
x = [6, 3, 8, 1, 7, 9, 3] , x = [6, 3, 2, 8, 9, 1, 5, 4]

In [17]:
# first we will sort them then we will remove one from each side until there is one left this will be the median and if there is two left we will add them and divide them by 2
# for the first x after sorting(1,3,3,6,7,8,9) then after crossing left and right the median is 6
l1=(1,3,3,6,7,8,9)
print(np.median(l1))
# for the second x after sorting(1,2,3,4,5,6,8,9) then after crossing left and right 4,5 is left and the median is their average is 4.5 
l2=(1,2,3,4,5,6,8,9)
print(np.median(l2))

6.0
4.5


6-What is AI?

In [ ]:
# artifcial intellegence it is human_like intellegnce that can nearly think as humans, but without emotions

7-Why AI is used ?

In [ ]:
# it is used as it is faster then humans, more consistent, less human error, no decisions made based on feelings, saves money paid for people

8-When to use AI ?

In [ ]:
# it is used when there is enough data and there is a pattern in the process or somthing that happens over and over again so no need for humans to do it AI can replace them

9-What is  AI pipeline?

In [ ]:
#data collecting, feature engineering, model selection, train, test

10-AI is ....% Data Operations , and ..... Model Creation 

In [ ]:
# 80% data operations
# 20% model creation

11-how to convert data that not normal distribution to normal distribution?

In [ ]:
# get samples of the data and get their means then get their mean

11-What is Feature Engineering? 

In [ ]:
# he is the engineer that removes tha unuseful data from the data to make it ready to enter to the model

12-How to avoid bad Sampling

In [ ]:
# remove outliers and don't take bias data

13-Why do we do Sampling?

In [ ]:
# as it is hard to get all the data as it may be too large to work on it at the same time due to not enough storage or not enough ram or it could be costy and time consuming to work on the whole data  

14-What is a programming language?

In [ ]:
# it is a language that the programmers write in so that the computer can understand what they want and there is high level language that is near the english language that we speak and there is low level language that is near to computers and faster to compile as assembly 

15-Create a random vector of size 30 and find the mean value

In [21]:
arr15=np.random.rand(30)
print(arr15)
print(arr15.mean())

[0.79335387 0.90709749 0.72355737 0.86265447 0.64763105 0.10248231
 0.81039685 0.32185662 0.29179238 0.7558597  0.04072109 0.89222121
 0.11051055 0.29353642 0.08092421 0.51756835 0.90268376 0.15435381
 0.54238028 0.30574253 0.72583516 0.63225657 0.52229349 0.65230306
 0.75921158 0.45424179 0.42574798 0.01278768 0.62349122 0.82021769]
0.5228570179122585


16-Create a 10x10 array with random values and find the minimum and maximum values

In [24]:
arr16=np.random.rand(100).reshape(10,10)
print(arr16)
print(arr16.max())
print(arr16.min())

[[0.46396851 0.13829113 0.91980175 0.51933185 0.57097452 0.72199759
  0.6738824  0.81181003 0.87886448 0.54739636]
 [0.94810368 0.14992626 0.87495114 0.29166172 0.9483205  0.40723529
  0.7304923  0.22978869 0.39639106 0.99526919]
 [0.43494105 0.15220921 0.95884613 0.05748467 0.44374837 0.18327002
  0.92295889 0.52095901 0.05500838 0.77282956]
 [0.6450588  0.97781236 0.17704328 0.79267244 0.39455973 0.21953939
  0.22314007 0.9231466  0.82280505 0.72095892]
 [0.09793438 0.94658334 0.37191746 0.08814018 0.21093213 0.76040869
  0.56288456 0.6787552  0.04157885 0.60559136]
 [0.69657956 0.77035537 0.19595607 0.79119588 0.11508053 0.25832508
  0.8176668  0.75956898 0.36125326 0.36465729]
 [0.48165291 0.27935152 0.55423733 0.63405753 0.68563802 0.110756
  0.69279418 0.1547348  0.4288648  0.30546336]
 [0.70457925 0.05127024 0.35625614 0.54327966 0.83541795 0.75535455
  0.47010979 0.46803145 0.49333518 0.67618061]
 [0.05589958 0.25847561 0.32650664 0.67837403 0.67060626 0.60180359
  0.07706032 0

17- Write a NumPy program to create a 2D array with 1 on the border and 0 inside

# 

In [28]:
arr17=np.ones(4).reshape(2,2)
arr17

array([[1., 1.],
       [1., 1.]])

18-Create a 8x8 matrix and fill it with a checkerboard pattern

# 

In [30]:
arr18=np.tile([[1,0],[0,1]],(4,4))
arr18

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

19-generates a 5x5 NumPy array filled with random integers from 1 to 99.

In [32]:
arr19=np.random.randint(1,99,(5,5))
arr19

array([[47, 70, 68, 82, 31],
       [ 9, 60, 85, 26, 36],
       [58, 36, 42, 42, 57],
       [14, 85, 83, 47, 83],
       [57, 29, 43, 80, 29]])

20-mean,std,mim and max

In [41]:
print(arr19.mean())
print(arr19.std())
print(arr19.min())
print(arr19.max())

51.96
22.649467984921852
9
85


21-what is Types of Data

In [ ]:
# it represnts how the data is stored and how it can be dealt with as for example integers takes less storage than floats: continous and discrete

22-calc the Z score x=25 ,std=5 ,mean= 20

In [33]:
Z=(25-5)/20
print(Z)

1.0


23-Create a list of theses elements : 1,3,4,16,17,20, "Ahmed", "Mazen", True

In [47]:
l23=[1,3,4,16,17,20,"Ahmed","Mazen",True]
l23

[1, 3, 4, 16, 17, 20, 'Ahmed', 'Mazen', True]

24-add 7 to the list 

In [48]:
l23.append(7)
l23

[1, 3, 4, 16, 17, 20, 'Ahmed', 'Mazen', True, 7]

25-remove 3 from the list 

In [49]:
l23.remove(3)
l23

[1, 4, 16, 17, 20, 'Ahmed', 'Mazen', True, 7]

26-Count how many numbers 4 has occured

In [50]:
l23.count(4)

1

l23.count(4)

27-print only the even numbers in the list

In [60]:
for i in l23:
    if str(i).isdigit(): 
        if i%2==0:
            print(i)

4
16
20


28-Sum only the numeric elements in the list

In [63]:
sum1=0
for i in l23:
    if str(i).isdigit(): 
        if i%2==0:
            sum1+=i
print(sum1)

40


29-When must we use Assembly?

In [ ]:
# when we need to run something fastly and on a small device with small storage and small ram 

30-Why Companies can't move from OOP to Functional programming?

In [ ]:
# as OOP is more organised, more maitainable, so that teams can work on it together easily and understand eachothers work 

31- Agile and waterfall


In [ ]:
# Agile is that we divide the whole project into cycles and each cycle takes 2-3 weeks where each department work on their part and show it to the costumer instead of waterfall where it is npt a cycle but a flow where each deparment work after the other and shows it to the client at the end 

32-What is Sample Size ?

# 30

33-Why do we do Sampling?

34-What are the types of medical image files?

In [ ]:
#.png, .jpg

35-what is series?

In [ ]:
# it is like a numpy array where all the data are of the same type

36-Create pandas dataframe as input from users

name, age, id, gender, email, phone number, city,

then

a. group by city
b. which city has the most students
c. get the average of ages for each gender
d. plot the relation between number of males to females
e. plot the relation between age and gender

In [67]:
import pandas as pd
name=[]
age=[]
id1=[]
gender=[]
email=[]
phone=[]
city=[]
n=int(input('enter the number of people: '))
for i in range(n):
    cn=input('enter the name: ')
    ca=int(input('enter the age: '))
    ci=int(input('enter the id: '))
    cg=input('enter the gender: ')
    ce=input('enter the email: ')
    cp=input('enter the phone: ')
    cc=input('enter the city: ')
    name.append(cn)
    age.append(ca)
    id1.append(ci)
    gender.append(cg)
    email.append(ce)
    phone.append(cp)
    city.append(cc)

enter the number of people: 3
enter the name: ahmed
enter the age: 20
enter the id: 111
enter the gender: M
enter the email: ah.g
enter the phone: 0100
enter the city: cairo
enter the name: mahmoud
enter the age: 15
enter the id: 222
enter the gender: M
enter the email: mh.g
enter the phone: 020
enter the city: giza
enter the name: nour
enter the age: 19
enter the id: 333
enter the gender: F
enter the email: nr.g
enter the phone: 030
enter the city: cairo


In [98]:
df=pd.DataFrame({'name':name,'age':age,'ID':id1,'gender':gender,'email':email,'phone':phone,'city':city})
g=df.groupby('city',axis=1)

In [95]:
df.city.value_counts()

cairo    2
giza     1
Name: city, dtype: int64

In [118]:
avgm=df['age'][df['gender']=='M'].mean()
avgf=df['age'][df['gender']=='F'].mean()
print(avgm)
print(avgf)

17.5
19.0


In [111]:
import matplotlib.pyplot as plt
%matplotlib inline

In [124]:
countm=0
countf=0
for i in df.gender:
    if i=='M':
        countm+=1
    else:
        countf+=1
genders=['m','f']
l90=[countm,countf]
print(l90)
plt.bar(genders,l90)

[2, 1]


<BarContainer object of 2 artists>

In [125]:
plt.plot(df.age,df.gender)

In [135]:

# Exercises

#Follow the instructions to recreate the plots using this data:

## Data

import numpy as np
x = np.arange(0,100)
y = x*2
z = x**2

import matplotlib.pyplot as plt
%matplotlib inline

## Exercise 1

** Follow along with these steps: **
* ** Create a figure object called fig using plt.figure() **
* ** Use add_axes to add an axis to the figure canvas at [0,0,1,1]. Call this new axis ax. **
* ** Plot (x,y) on that axes and set the labels and titles to match the plot below:**


In [139]:
fig=plt.figure()
ax=fig.add_axes([0,0,1,1])
plt.plot(x,y,label='y=2x')
plt.legend()
plt.title('linear straight line')
plt.xlabel('x axis')
plt.ylabel('y axis')

Text(0, 0.5, 'y axis')

## Exercise 2
** Create a figure object and put two axes on it, ax1 and ax2. Located at [0,0,1,1] and [0.2,0.5,.2,.2] respectively.**


In [142]:
fig2=plt.figure()
ax1=fig.add_axes([0,0,1,1])
ax2=fig.add_axes([0.2,0.5,0.2,0.2])
plt.show()

<Figure size 640x480 with 0 Axes>