In [2]:
import numpy as np
arr=np.arange(0,101,10)
print(arr)
print(arr.size)

[  0  10  20  30  40  50  60  70  80  90 100]
11


In [3]:
l=[1,2,3]
arr=np.array(l)
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


In [6]:
arr,stp=np.linspace(0,10,3,endpoint=False,retstep=True)
print(arr)
print(stp)

[0.         3.33333333 6.66666667]
3.3333333333333335


In [9]:
arr=np.array(range(0,100,10))
print(arr)
arr=arr.reshape(2,5)
print(arr)

[ 0 10 20 30 40 50 60 70 80 90]
[[ 0 10 20 30 40]
 [50 60 70 80 90]]


In [13]:
arr=np.array((10,20,14))
arr.apennd(15)
print(arr)

AttributeError: 'numpy.ndarray' object has no attribute 'apennd'

In [22]:
arr=np.arange(0,64)
print(arr)
count=0
z=0
for i in arr:
    if z%2==0:
        arr[count]=1
    else:
        arr[count]=0
    count+=1
    z+=1
    if z==8:
        z=1
    if z==7:
        z=0
arr=arr.reshape(8,8)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63]
[[1 0 1 0 1 0 1 1]
 [0 1 0 1 0 1 1 0]
 [1 0 1 0 1 1 0 1]
 [0 1 0 1 1 0 1 0]
 [1 0 1 1 0 1 0 1]
 [0 1 1 0 1 0 1 0]
 [1 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 1]]
