In [2]:
import numpy as np
arr1=np.array(range(0,51))
arr2=np.array(range(10,51))
print(arr1)
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [6]:
a=int(input('enter: '))
b=a//365
c=(a-365*b)//30
d=((a-365*b)-c*30)
print(b)
print(c)
print(d)

enter: 400
1
1
5


In [8]:
import numpy as np
arr=np.ones((4,4))
print(arr)
for i in arr[:,]:
    if i!=1 or i!=4:
        arr[i]=0
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [11]:
import numpy as np
arr=np.ones((4,4))
print(arr)
arr[1:3,1:3]=0
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]
